### ISSUE TITLE
i believe their is a easier way to add the ico that takes up less space btw.

### ISSUE THREAD

**Issue by Ashui-Idiot** [The0Show/utilman-hack#1]
so for the html file commit add this: 
`<link rel="shortcut icon" type="image/jpg" href="/(the file)"/>`
makes it more high quality- and i think can end up taking up leass space.
(did this cause im to much of a idiot to do pull reqs.)

**Comment by The0Show** [comment]
Thanks for submitting the issue! Unfortunately this doesn't do anything to the app, but it was a good idea to try out.
